### ISSUE TITLE
Add a document to add route to host machine

### ISSUE THREAD

**Issue by TsutomuNakamura** [tsuna-server/build-dev-server-ansible#1]
After `build-dev-server-ansible` was executed, user have to add route config to connect to the management network.
User set the provider network as `192.168.1.0/24` and management network as `192.168.2.0/24` for example, user have to set route config on their host machine like below.

```
# ip route add 192.168.2.0/24 via 192.168.1.254
```

The IP `192.168.1.254` is a gateway IP that the use set before running Ansible.

* group_vars/all
```
group_vars:
  vxlan:
    provider:
      interface: br0
      ip: 192.168.1.254/24
      ......
```
