### ISSUE TITLE
Added a feature to create detailed partition.

### ISSUE THREAD

**Issue by TsutomuNakamura** [tsuna-server/build-dev-server-ansible#23]

**Comment by TsutomuNakamura** [comment]
I will implement it by using a feature of auto-install in ubuntu. It will NOT support other Linux distributions. Supports of other distributions will not consider in this issue.

**Comment by TsutomuNakamura** [comment]
To enable this feature, this program installs OS from normal image not cloud image. cloud-image has already partitioned on a qcow2 file.

**Comment by TsutomuNakamura** [comment]
* cloud_init.cfg
```
#cloud-config
autoinstall:
  ssh:
    install-server: True
    authorized-keys: ['ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOETK2IbbTPHajYDIUaXAtmPL04P+MZQI7VKjSB0sxkL TsutomuNakamura@github.com']
  identity:
    username: sushi7
    password: $6$xyz$rfUoxhnScmjOykLAVIhgfxmKgIWmTirRSrIZ9j5EJ1Vf765rQS.dCbXjXBx4PuhbcNNrXx2XpwUywQ96C7EJB/
  storage:
    grub:
      reorder_uefi: False
    config: [{'id': 'disk-vda', 'type': 'disk', 'name': 'osdisk', 'ptable': 'gpt', 'path': '/dev/vda', 'wipe': 'superblock-recursive', 'preserve': False, 'grub_device': True}, {'id': 'part-efi', 'type': 'partition', 'device': 'disk-vda', 'size': '512M', 'flag': 'boot', 'preserve': False, 'partition_type': 'EF00', 'wipe': 'superblock', 'grub_device': True}, {'id': 'part-boot', 'type': 'partition', 'device': 'disk-vda', 'size': '512M'}, {'id': 'part-pv01', 'type': 'partition', 'device': 'disk-vda', 'size': -1, 'flag': 'lvm', 'preserve': False, 'wipe': 'superblock'}, {'id': 'lvm-vg01', 'type': 'lvm_volgroup', 'name': 'lvm-vg01', 'devices': ['part-pv01']}, {'id': 'lvm-vg01-log', 'type': 'lvm_partition', 'name': 'lvm-vg01-log', 'size': '4G', 'volgroup': 'lvm-vg01'}, {'id': 'lvm-vg01-root', 'type': 'lvm_partition', 'name': 'lvm-vg01-root', 'size': '16G', 'volgroup': 'lvm-vg01'}, {'id': 'format-efi', 'type': 'format', 'volume': 'part-efi', 'fstype': 'vfat'}, {'id': 'format-boot', 'type': 'format', 'volume': 'part-boot', 'fstype': 'ext4'}, {'id': 'format-root', 'type': 'format', 'volume': 'lvm-vg01-root', 'fstype': 'xfs'}, {'id': 'format-log', 'type': 'format', 'volume': 'lvm-vg01-log', 'fstype': 'xfs'}, {'id': 'mount-boot', 'type': 'mount', 'device': 'format-boot', 'path': '/boot'}, {'id': 'mount-efi', 'type': 'mount', 'device': 'format-efi', 'path': '/boot/efi'}, {'id': 'mount-root', 'type': 'mount', 'device': 'format-root', 'path': '/'}, {'id': 'mount-log', 'type': 'mount', 'device': 'format-log', 'path': '/var/log'}]
  packages: ['iptables-persistent', 'netfilter-persistent', 'bridge-utils']
  network:
    version: 2
    ethernets:
      enp1s0:
        dhcp4: False
        dhcp6: False
        gateway4: 172.31.0.1
        nameservers:
          addresses: ['172.31.0.1', '8.8.8.8', '8.8.4.4']
        addresses: ['172.31.130.1/16']
      enp2s0:
        dhcp4: False
        dhcp6: False
      enp3s0:
        dhcp4: False
        dhcp6: False
      enp4s0:
        dhcp4: False
        dhcp6: False
      enp5s0:
        dhcp4: False
        dhcp6: False
      enp6s0:
        dhcp4: False
        dhcp6: False
    bridges:
      br1:
        interfaces: ['enp3s0', 'enp4s0', 'enp5s0', 'enp6s0']
  late-commands: ['echo "sushi7 ALL=(ALL) NOPASSWD:ALL" > /target/etc/sudoers.d/99-user-sushi7', 'echo "*nat"                                                                     >  /target/etc/iptables/rules.v4', 'echo ":PREROUTING ACCEPT [0:0]"                                                 >> /target/etc/iptables/rules.v4', 'echo ":INPUT ACCEPT [0:0]"                                                      >> /target/etc/iptables/rules.v4', 'echo ":OUTPUT ACCEPT [0:0]"                                                     >> /target/etc/iptables/rules.v4', 'echo ":POSTROUTING ACCEPT [0:0]"                                                >> /target/etc/iptables/rules.v4', 'echo "--append POSTROUTING --source 172.28.0.0/16 -o enp1s0 --jump MASQUERADE"  >> /target/etc/iptables/rules.v4', 'echo "COMMIT"                                                                   >> /target/etc/iptables/rules.v4', 'echo "*filter"                                                                  >> /target/etc/iptables/rules.v4', 'echo ":INPUT ACCEPT [0:0]"                                                      >> /target/etc/iptables/rules.v4', 'echo ":FORWARD ACCEPT [0:0]"                                                    >> /target/etc/iptables/rules.v4', 'echo ":OUTPUT ACCEPT [0:0]"                                                     >> /target/etc/iptables/rules.v4', 'echo "COMMIT"                                                                   >> /target/etc/iptables/rules.v4', 'echo "net.ipv4.ip_forward = 1"                                                  >  /target/etc/sysctl.d/98-forward.conf']

resize_rootfs: false
ssh_deletekeys: false
```

* network_config.cfg
```
version: 2
ethernets:
  enp1s0:
    dhcp4: False
    dhcp6: False
    gateway4: 172.31.0.1
    nameservers:
      addresses: ['172.31.0.1', '8.8.8.8', '8.8.4.4']
    addresses: ['172.31.130.1/16']
  enp2s0:
    dhcp4: False
    dhcp6: False
  enp3s0:
    dhcp4: False
    dhcp6: False
  enp4s0:
    dhcp4: False
    dhcp6: False
  enp5s0:
    dhcp4: False
    dhcp6: False
  enp6s0:
    dhcp4: False
    dhcp6: False
bridges:
  br1:
    interfaces: ['enp3s0', 'enp4s0', 'enp5s0', 'enp6s0']
```

**Comment by TsutomuNakamura** [comment]
[cloud-image-ubuntu-from-scratch](https://github.com/mvallim/cloud-image-ubuntu-from-scratch)
```
DEBIAN_FRONTEND=noninteractive sudo apt-get -y update
DEBIAN_FRONTEND=noninteractive sudo apt-get -y install \
   debootstrap \
   qemu-utils \
   qemu-system \
   genisoimage
```
```
mkdir $HOME/cloud-image-ubuntu-from-scratch
```
```
cd $HOME/cloud-image-ubuntu-from-scratch
```
```
dd if=/dev/zero of=cloud-ubuntu-image.raw bs=1 count=0 seek=32212254720 status=progress
```

```
sgdisk -z cloud-ubuntu-image.raw
sgdisk -n 1:0:+512M -t 1:ef00 -c 1:"EFI System" cloud-ubuntu-image.raw
sgdisk -n 2:0:+512M -t 2:8300 -c 2:"Linux filesystem" cloud-ubuntu-image.raw
sgdisk -n 3:0: -t 3:8e00 -c 3:"Linux LVM" cloud-ubuntu-image.raw
```

```
sudo losetup -fP cloud-ubuntu-image.raw
sudo losetup -a | grep cloud-ubuntu-image.raw
> /dev/loop3: [64769]:201335002 (/root/cloud-image-ubuntu-from-scratch/cloud-ubuntu-image.raw)
```

In this example, the loop device was created as /dev/loop3.
Set the variable L_DEV=/dev/loop3.

```
L_DEV=/dev/loop3
```

```
sudo gdisk -l ${L_DEV}
> ...
> Number  Start (sector)    End (sector)  Size       Code  Name
>    1            2048         1050623   512.0 MiB   EF00  EFI System
>    2         1050624         2099199   512.0 MiB   8300  Linux filesystem
>    3         2099200        54237190   24.9 GiB    8E00  Linux LVM

ls -l ${L_DEV}*
> brw-rw---- 1 root disk   7, 4 Mar 18 14:46 /dev/loop3
> brw-rw---- 1 root disk 259, 0 Mar 18 14:46 /dev/loop3p1
> brw-rw---- 1 root disk 259, 1 Mar 18 14:46 /dev/loop3p2
> brw-rw---- 1 root disk 259, 2 Mar 18 14:46 /dev/loop3p3
```

```
mkfs.vfat -F32 ${L_DEV}p1
mkfs.ext4 ${L_DEV}p2
pvcreate ${L_DEV}p3
vgcreate lvm-vg01 ${L_DEV}p3
lvcreate -L 4G -n lvm-vg01-log lvm-vg01
lvcreate -l 100%FREE -n lvm-vg01-root lvm-vg01
mkfs.xfs /dev/lvm-vg01/lvm-vg01-log
mkfs.xfs /dev/lvm-vg01/lvm-vg01-root
```

```
cd $HOME/cloud-image-ubuntu-from-scratch
mkdir chroot
sudo mount /dev/lvm-vg01/lvm-vg01-root chroot/
sudo mkdir -p chroot/var/log
sudo mount /dev/lvm-vg01/lvm-vg01-log chroot/var/log
sudo mkdir -p chroot/boot
sudo mount ${L_DEV}p2 chroot/boot
sudo mkdir -p chroot/boot/efi
sudo mount ${L_DEV}p1 chroot/boot/efi
```

```
sudo debootstrap \
   --arch=amd64 \
   --variant=minbase \
   --components "main,universe" \
   --include "ca-certificates,cron,iptables,isc-dhcp-client,libnss-myhostname,ntp,ntpdate,rsyslog,ssh,sudo,dialog,whiptail,man-db,curl,dosfstools,e2fsck-static" \
   jammy \
   $HOME/cloud-image-ubuntu-from-scratch/chroot \
   http://jp.archive.ubuntu.com/ubuntu/
```

```
# sudo mount --bind /dev $HOME/cloud-image-ubuntu-from-scratch/chroot/dev
# sudo mount --bind /run $HOME/cloud-image-ubuntu-from-scratch/chroot/run
# #sudo mount --bind /sys $HOME/cloud-image-ubuntu-from-scratch/chroot/sys
# #sudo mount --bind /proc $HOME/cloud-image-ubuntu-from-scratch/chroot/proc

sudo mount --rbind /dev $HOME/cloud-image-ubuntu-from-scratch/chroot/dev
sudo mount --rbind /run $HOME/cloud-image-ubuntu-from-scratch/chroot/run
sudo mount --rbind /sys $HOME/cloud-image-ubuntu-from-scratch/chroot/sys
sudo mount --rbind /proc $HOME/cloud-image-ubuntu-from-scratch/chroot/proc
```

```
sudo chroot $HOME/cloud-image-ubuntu-from-scratch/chroot /usr/bin/env L_DEV=${L_DEV} /bin/bash --login
```

```
# mount none -t proc /proc
# mount none -t sysfs /sys
# mount none -t devpts /dev/pts
export HOME=/root
export LC_ALL=C
```

```
echo "anonymous" > /etc/hostname
```

```
cat << EOF > /etc/apt/sources.list
deb http://jp.archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse
deb-src http://jp.archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse

deb http://jp.archive.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
deb-src http://jp.archive.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse

deb http://jp.archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe multiverse
deb-src http://jp.archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe multiverse
EOF
```

```
blkid ${L_DEV}*
> /dev/loop3: PTUUID="ffa96a9e-a534-402e-9e42-ec3e9ce92118" PTTYPE="gpt"
> /dev/loop3p1: UUID="BB34-0305" BLOCK_SIZE="512" TYPE="vfat" PARTLABEL="EFI System" PARTUUID="394a0967-ed11-42d7-b885-c2d4f87e0b2b"
> /dev/loop3p2: UUID="2c742071-7c57-44ce-85da-4b54e6311dd4" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="Linux filesystem" PARTUUID="e028c4a6-a3f8-4f48-b691-65065f3cfc8d"
> /dev/loop3p3: UUID="yKTvg5-k6BP-SjAa-aB3Z-WB29-PRFJ-aKtfSX" TYPE="LVM2_member" PARTLABEL="Linux LVM" PARTUUID="a7159554-574f-450d-8e8f-c6a4f4811b12"

blkid /dev/mapper/lvm--vg01-lvm--vg01*
> /dev/mapper/lvm--vg01-lvm--vg01--log: UUID="4a5de200-8d56-4b4d-980d-689cfccbd021" BLOCK_SIZE="512" TYPE="xfs"
> /dev/mapper/lvm--vg01-lvm--vg01--root: UUID="05d7611d-e724-44d1-8ea7-bc64babadbcb" BLOCK_SIZE="512" TYPE="xfs"
```

```
cat << EOF > /etc/fstab
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system>         <mount point>   <type>  <options>                       <dump>  <pass>

UUID="05d7611d-e724-44d1-8ea7-bc64babadbcb" / xfs rw,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota        0 1
UUID="2c742071-7c57-44ce-85da-4b54e6311dd4" /boot ext4 rw,relatime     0 2
UUID="BB34-0305"       /boot/efi       vfat    rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro   0 2
UUID="4a5de200-8d56-4b4d-980d-689cfccbd021" /var/log xfs rw,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota        0 1
EOF
```

```
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y systemd-sysv
```

```
dbus-uuidgen > /etc/machine-id
ln -fs /etc/machine-id /var/lib/dbus/machine-id
```

```
dpkg-divert --local --rename --add /sbin/initctl
ln -s /bin/true /sbin/initctl
```

```
DEBIAN_FRONTEND=noninteractive apt-get install -y \
    xfsprogs os-prober ifupdown \
    network-manager resolvconf locales \
    build-essential module-assistant cloud-init \
    grub2 grub-pc linux-generic
```

```
cat <<EOF > /etc/network/interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback
EOF
```

Set locale.

```
# https://serverfault.com/a/689947
echo "Asia/Tokyo" > /etc/timezone
dpkg-reconfigure -f noninteractive tzdata

sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
sed -i -e 's/# ja_JP.UTF-8 UTF-8/ja_JP.UTF-8 UTF-8/' /etc/locale.gen
dpkg-reconfigure --frontend=noninteractive locales
update-locale LANG=en_US.UTF-8
```

```
dpkg-reconfigure resolvconf -f noninteractive
```

```
cat <<EOF > /etc/NetworkManager/NetworkManager.conf
[main]
rc-manager=resolvconf
plugins=ifupdown,keyfile
dns=default

[ifupdown]
managed=false
EOF
```

```
dpkg-reconfigure network-manager -f noninteractive
```

```
apt-get install -y grub-efi
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=arch --boot-directory=/boot/efi/EFI --recheck
update-grub
```

Finished to prepare resources for the cloud image.
Following this instruction, we will create the cloud image(qcow2) from the raw image.

```
truncate -s 0 /etc/machine-id
rm /sbin/initctl
dpkg-divert --rename --remove /sbin/initctl

apt-get clean
rm -rf /tmp/* ~/.bash_history
#umount /proc
#umount /sys
#umount /dev/pts
export HISTSIZE=0
exit
```

Chroot environment was finished.

```
cd $HOME/cloud-image-ubuntu-from-scratch
sudo umount $HOME/cloud-image-ubuntu-from-scratch/chroot/boot/efi
sudo umount $HOME/cloud-image-ubuntu-from-scratch/chroot/boot
sudo umount $HOME/cloud-image-ubuntu-from-scratch/chroot/var/log
sudo umount $HOME/cloud-image-ubuntu-from-scratch/chroot/

sudo umount $HOME/cloud-image-ubuntu-from-scratch/chroot/dev
sudo umount $HOME/cloud-image-ubuntu-from-scratch/chroot/run
sudo umount $HOME/cloud-image-ubuntu-from-scratch/chroot/sys
sudo umount $HOME/cloud-image-ubuntu-from-scratch/chroot/proc



sudo losetup -D
```

Convert raw to qcow2.

```
qemu-img convert -f raw cloud-ubuntu-image.raw -O qcow2 ubuntu-image.qcow2
```

**Comment by TsutomuNakamura** [comment]
How to boot from grub prompt.
https://superuser.com/questions/1237684/how-to-boot-from-grub-shel

https://bbs.archlinux.org/viewtopic.php?id=201147

https://unix.stackexchange.com/a/420489

**Comment by TsutomuNakamura** [comment]
Failed to boot the OS after qcow2 disk has created.

**Comment by TsutomuNakamura** [comment]
To unmount /dev
```
mount --make-rslave dev/
umount -R dev/
```
https://unix.stackexchange.com/questions/549945/how-do-i-unmount-dev-after-mounting-it

**Comment by TsutomuNakamura** [comment]
Succeeded in creating bootable qcow2 image. The journal is in [here](https://github.com/hobby-labs/note2/tree/master/07_CreateUbuntuBootableQcow2Disk).

**Comment by TsutomuNakamura** [comment]
# Testing

```
IMAGE_BASE_DIR=/var/kvm/iso
INSTANCE_BASE_DIR=/var/kvm/distros/stg-controller01
mkdir -p ${INSTANCE_BASE_DIR}
mkdir -p ${IMAGE_BASE_DIR}
```

* cloud_init.cfg
```
cat << 'EOF' > ${INSTANCE_BASE_DIR}/cloud_init.cfg
#cloud-config
hostname: stg-controller01
fqdn: stg-controller01.example.com
manage_etc_hosts: true
users:
  - name: sushi7
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/sushi7
    shell: /bin/bash
    # TODO: For debugging purpose only, you can set the user's password as 'p@ssw0rd' by declaring `passwd` like below.
    #       You can also create new passwd manually by typing like below.
    #         openssl passwd -6 -salt xyz  yourpass
    #       See also: https://unix.stackexchange.com/questions/81240/manually-generate-password-for-etc-shadow
    passwd: $6$xyz$rfUoxhnScmjOykLAVIhgfxmKgIWmTirRSrIZ9j5EJ1Vf765rQS.dCbXjXBx4PuhbcNNrXx2XpwUywQ96C7EJB/
    lock_passwd: false
    #ssh-authorized-keys:
    #  - ...
# only cert auth via ssh (console access can still login)
ssh_pwauth: false
disable_root: false
chpasswd:
  list: |
    ubuntu:linux
  expire: False

package_update: true
packages:
  - qemu-guest-agent
# written to /var/log/cloud-init-output.log
final_message: "The system is finally up, after $UPTIME seconds"
EOF
```

* network_config.cfg
```
cat << 'EOF' > ${INSTANCE_BASE_DIR}/network_config.cfg
version: 2
ethernets:
  enp1s0:
    dhcp4: False
    dhcp6: False
    gateway4: 172.31.0.1
    nameservers:
      addresses: ['172.31.0.1', '8.8.8.8', '8.8.4.4']
    addresses: ['172.31.130.1/16']
  enp2s0:
    dhcp4: False
    dhcp6: False
  enp3s0:
    dhcp4: False
    dhcp6: False
  enp4s0:
    dhcp4: False
    dhcp6: False
  enp5s0:
    dhcp4: False
    dhcp6: False
  enp6s0:
    dhcp4: False
    dhcp6: False
bridges:
  br1:
    interfaces: ['enp3s0', 'enp4s0', 'enp5s0', 'enp6s0']
EOF
```

```
cd ${INSTANCE_BASE_DIR}/
cloud-localds -v --network-config network_config.cfg stg-controller01-seed.img cloud_init.cfg
```

```
qemu-img create -F qcow2 -b ${IMAGE_BASE_DIR}/stg-controller.qcow2 -f qcow2 ${INSTANCE_BASE_DIR}/stg-controller01.img
```

```
mkdir -p ${INSTANCE_BASE_DIR}
virt-install \
    --name stg-controller01 --boot uefi --import \
    --connect=qemu:///system --vcpus=2 --memory 16384 \
    --disk path=${INSTANCE_BASE_DIR}/stg-controller01.img \
    --disk path=${INSTANCE_BASE_DIR}/stg-controller01-seed.img,device=cdrom \
    --os-variant=ubuntu22.04 --arch x86_64 \
    --network bridge:br0,mac=52:54:00:00:00:10 \
    --network bridge:br1,mac=52:54:00:00:00:11 \
    --network bridge:br1,mac=52:54:00:00:00:12 \
    --graphics vnc,port=15901,listen=127.0.0.1,password=changeme
virsh destroy stg-controller01; virsh undefine stg-controller01 --nvram; rm -rf ${INSTANCE_BASE_DIR}
```
