### ISSUE TITLE
External snapshot of qcow2 and UEFI and LVM does not work

### ISSUE THREAD

**Issue by TsutomuNakamura** [tsuna-server/build-dev-server-ansible#24]

**Comment by TsutomuNakamura** [comment]
Test it manually. It might cause only when cloud-config file is also mounted as cdrom.

**Comment by TsutomuNakamura** [comment]
```
BASE_IMAGE_DIR="/path/to/distros"
DEST_IMAGE_DIR="${BASE_IMAGE_DIR}/stg-controller01"
mkdir -p "${DEST_IMAGE_DIR}"
cd "${DEST_IMAGE_DIR}"
qemu-img create -F qcow2 -b ../stg-controller.qcow2 -f qcow2 stg-controller01.img
virt-install \
    --name stg-controller01 --boot uefi --import \
    --connect=qemu:///system --vcpus=2 --memory 16384 \
    --disk path=${DEST_IMAGE_DIR}/stg-controller.qcow2 \
    --os-variant=ubuntu22.04 --arch x86_64 \
    --network bridge:br0 \
    --network bridge:br1 \
    --graphics vnc,port=15901,listen=127.0.0.1,password=changeme
```

**Comment by TsutomuNakamura** [comment]
```
BASE_IMAGE_DIR="/path/to/distros"
DEST_IMAGE_DIR="${BASE_IMAGE_DIR}/stg-controller01"
mkdir -p "${DEST_IMAGE_DIR}"
cd "${DEST_IMAGE_DIR}"
```
```
cat << 'EOF' > network_config.cfg
version: 2
ethernets:
  enp1s0:
    dhcp4: False
    dhcp6: False
    gateway4: 172.31.0.1
    nameservers:
      addresses: ['172.31.0.1', '8.8.8.8', '8.8.4.4']
    addresses: ['172.31.130.1/16']
  enp2s0:
    dhcp4: False
    dhcp6: False

bridges:
  br1:
    interfaces: ['enp3s0', 'enp4s0', 'enp5s0', 'enp6s0']
EOF
```
```
cat << 'EOF' > cloud_init.cfg
#cloud-config
hostname: stg-controller01
fqdn: stg-controller01.example.com
manage_etc_hosts: true
users:
  - name: me
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/me
    shell: /bin/bash
    # TODO: For debugging purpose only, you can set the user's password as 'p@ssw0rd' by declaring `passwd` like below.
    passwd: $6$xyz$rfUoxhnScmjOykLAVIhgfxmKgIWmTirRSrIZ9j5EJ1Vf765rQS.dCbXjXBx4PuhbcNNrXx2XpwUywQ96C7EJB/
    lock_passwd: false
# only cert auth via ssh (console access can still login)
ssh_pwauth: false
disable_root: false
chpasswd:
  list: |
    ubuntu:linux
  expire: False

package_update: true
packages:
  - qemu-guest-agent
# written to /var/log/cloud-init-output.log
final_message: "The system is finally up, after $UPTIME seconds"
EOF
```
```
cloud-localds -v --network-config network_config.cfg stg-controller02-seed.img cloud_init.cfg
qemu-img create -F qcow2 -b ../stg-controller.qcow2 -f qcow2 stg-controller01.img
```
```
/usr/bin/virt-install --name stg-controller01 \
    --virt-type kvm --memory 16384 \
    --vcpus 2 --boot uefi --import \
    --disk path=stg-controller01-seed.img,device=cdrom \
    --disk path=stg-controller01.img,device=disk \
    --os-variant ubuntu22.04 \
    --network bridge:br0 --network bridge:br1 \
    --graphics vnc,port=15901,listen=127.0.0.1,password=changeme
```
